import type { Metadata } from "next";
import Header from "@/components/header";
import "tailwindcss/tailwind.css";
import { Inter } from 'next/font/google'
import Footer from "@/components/footer";

const inter = Inter({weight: "300", subsets: ["latin"], style: "normal", display: "swap"})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={" px-20 " +  inter.className }>
        <Header/>
        <div className="text-3xl">{children}</div>
      </body>
      <Footer />
    </html>
  );
}
