# Generated by Django 5.0.7 on 2024-07-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_todolist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
