# Generated by Django 5.0.7 on 2024-07-27 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_todolist_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='created_at',
        ),
        migrations.AddField(
            model_name='todolist',
            name='created_At',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
