# Generated by Django 5.0.7 on 2024-07-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_todolist_created_at_todolist_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='created_At',
            new_name='created_at',
        ),
    ]
