# Generated by Django 5.0.7 on 2024-07-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_todolist_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
