# Generated by Django 5.0.7 on 2024-07-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_websiteviews_alter_todolist_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websiteviews',
            old_name='views',
            new_name='total_views',
        ),
    ]
