# Generated by Django 5.0.7 on 2024-07-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_websiteviews_total_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebsiteViews',
        ),
    ]
